### ISSUE TITLE
apicloud

### ISSUE THREAD

**Issue by Emyle** [mxchipSDK/Fog2.0#1]
Sin

您好，我看fog2.0的工程最近都在更新，我尝试着运行你上次告诉我的widget的包，但是真机同步时报错如下：

 

mico2模块未绑定

如果您使用了apploader进行调试，请在网站控制台绑定后编译正式版使用；

如果您使用了自定义loader进行调试，请绑定模块后重新编译自定义loader即可

Uncaught TypeError: Cannot read property 'init' of undefined at index.html : 21

 

我看在我们FOG2.0的github工程里并没有提供 micoMdns  micoMqtt2 micoBind这三个模块，我使用的是fog1.0里的模块加载的。见附件截图。总之就是mico2模块应该没绑定。请问是什么原因？谢谢

**Comment by bringmehome** [comment]
你用的是APICloud吧，你说的mico2模块在这里：https://github.com/mxchipSDK/Fog2.0/tree/master/APICloud/mico2%E8%B5%84%E6%BA%90%E5%8C%85

同样需要你自己上传到自定义模块里，我也会尽快上架。

**Comment by Emyle** [comment]
你好，Sin

哦，原来Fog2.0里把Fof1.0的三个micoMdns micoMqtt2 micoBind模块合并了，是吧？我大概了解了。

但是我按照你提供的链接。把Android和ios里的mico2.zip都上传到了apicloud控制平台上，然后重新编译apploader。还是提示 mico2模块未绑定。我也在排查问题，目前可能有以下三种情况或更多：

1）是不是mico2.zip的Android和ios包有问题？
2）我引入模块的语法拼写有问题?（我是按照你widget包里粘贴的，如下）
        var mico2;
	const host = {host:"https://iot.mxchip.com"};
        mico2 = api.require('mico2');
	mico2.init(host);
3）apploader没有编译过去？

我的apicloud平台账号：18810069007
                    平台密码：hocoohocoo

能否帮我确认下什么问题？

谢谢
kai

**Comment by Emyle** [comment]
mico2 项目

**Comment by bringmehome** [comment]
暂时没看明白那个mico2的项目出了什么问题，我新建了一个mico2_xxx，这个可以用

**Comment by bringmehome** [comment]
我倒是建议你删除这个工程，重新建一个试试。还有问题请联系我QQ：88635653

**Comment by Emyle** [comment]
已解决！感谢
