### ISSUE TITLE
旧版本FOG1.0的mico-ac-0.2.js中的MICO对象在FOG2.0里是？ 

### ISSUE THREAD

**Issue by Emyle** [mxchipSDK/Fog2.0#2]
您好，sin

如题。我现在想调用 mico-ac-0.2.js 中的 MiCO.getSmsCode方法。不知道在FOG2.0是怎么对应的？

祝好
凯光

**Comment by bringmehome** [comment]
你好，mico2中有专门获取短信验证码的接口，不需要通过js调用，而且mico-ac-0.2.js 只适用于老版本的，你要是打算用mico2，那么这个js可以抛弃了

**Comment by Emyle** [comment]
已解决。
