### ISSUE TITLE
APIcloud - MiCO2 - startEasyLink() 回调问题

### ISSUE THREAD

**Issue by Emyle** [mxchipSDK/Fog2.0#3]
Sin，你好！

关于startEasyLink()方法问题：
           var param = {
	        ssid: ssid_val,
	        password: psw_val,
	        runSecond: 10000
	    };
	    
	    mico2.startEasyLink(param, function(ret, err) {
	        if (ret) {
	            console.log(ret);
	            toast(ret.message);
	        } else {
	            alert(0);
	            toast(err.message);
	        }
	    });
问题1. 当我输入正确SSID后，再输入密码。然后点击开始配网。无论密码对或者错都会返回成功提示，即if(ret)为true
问题2. 此方法调用后好像有两次回调，一次是在初始调用成功后，有一次回调，走的是if (ret) ，另一次是在runSecond时间过后（配网结束），又走了一次if (ret) 。初始连接成功和配网结束回调是不是应该分开？
问题3. 如果我输入错误的wifi密码（SSID对应密码）。连接失败和密码错误也是在一个回调里面？

谢谢
凯光

**Comment by bringmehome** [comment]
1、这个接口并不会验证密码，只是告诉你接口调用成功，密码不填都没事
2、runsecond，是默认配网时间，设置这个的目的是防止忘记关闭配网导致网络阻塞
3、至于设备是否连接WiFi成功，这个接口并不能知道，需要通过搜索设备的接口去发现本地是否有设备连上WiFi了

综上，这个接口的目的就是在runsecond的有效时间内发送配网包给需要配网的设备，至于设备是否真的配上WiFi了，并不知道。

**Comment by Emyle** [comment]
谢谢Sin，理解这个方法了。

请问如果我想支持配网时SSID和密码是否匹配，easylink有类似接口或者方法吗？按你的经验应该怎么实现比较好。

**Comment by bringmehome** [comment]
目前没有这样的接口

**Comment by Emyle** [comment]
已解决
